if(NOT DEFINED ENV{FCFLAGS})
    if(CMAKE_Fortran_COMPILER_ID MATCHES GNU)
        set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -cpp -Wall -Wextra")
        set(CMAKE_Fortran_FLAGS_RELEASE "-O3 -funroll-all-loops")
        set(CMAKE_Fortran_FLAGS_DEBUG "-O0 -g -fbacktrace")
        if(CMAKE_Fortran_COMPILER_VERSION VERSION_GREATER_EQUAL "10.0.0")
            set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -fallow-argument-mismatch")
        endif()
    endif()
endif()
